<a href="https://colab.research.google.com/github/CodeBlue0001/ML-Linear_regresion/blob/main/nlp_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import nltk
nltk.download()
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

NLTK Downloader
---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------
Downloader> d

Download which package (l=list; x=cancel)?
  Identifier> d

    Error loading d: Package 'd' not found in index

---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------
Downloader> d

Download which package (l=list; x=cancel)?
  Identifier> l
Packages:
  [ ] abc................. Australian Broadcasting Commission 2006
  [ ] alpino.............. Alpino Dutch Treebank
  [ ] averaged_perceptron_tagger Averaged Perceptron Tagger
  [ ] averaged_perceptron_tagger_eng Averaged Perceptron Tagger (JSON)
  [ ] averaged_perceptron_tagger_ru Averaged Perceptron Tagger (Russian)
  [ ] averaged_perceptron_tagger_rus Averaged Perceptron Tagger (Russian)
  [ ] basque_grammars..... Grammars for Basque
  [ ] bcp47............... BCP-47 Language Tags
  [ ] biocreative_ppi..... BioCreAtIvE (Critical Assessment of Information
                           Extraction Systems in Biology)
  [ ] bllip_wsj_no_aux.... BLLIP Parser: WSJ Model
  [ ] book_grammars....... Grammars from NLTK Book
  [ ] brown............... Brown Corpus
  [ ] brown_tei........... Brown Corpus (TEI XML Version)
  [ ] cess_cat............ CESS-CAT Treebank
  [ ] cess_esp............ CESS-ESP Treebank
  [ ] chat80.............. Chat-80 Data Files
  [ ] city_database....... City Database
  [ ] cmudict............. The Carnegie Mellon Pronouncing Dictionary (0.6)
  [ ] comparative_sentences Comparative Sentence Dataset
Hit Enter to continue:
  [ ] comtrans............ ComTrans Corpus Sample
  [ ] conll2000........... CONLL 2000 Chunking Corpus
  [ ] conll2002........... CONLL 2002 Named Entity Recognition Corpus
  [ ] conll2007........... Dependency Treebanks from CoNLL 2007 (Catalan
                           and Basque Subset)
  [ ] crubadan............ Crubadan Corpus
  [ ] dependency_treebank. Dependency Parsed Treebank
  [ ] dolch............... Dolch Word List
  [ ] english_wordnet..... Open English Wordnet
  [ ] europarl_raw........ Sample European Parliament Proceedings Parallel
                           Corpus
  [ ] extended_omw........ Extended Open Multilingual WordNet
  [ ] floresta............ Portuguese Treebank
  [ ] framenet_v15........ FrameNet 1.5
  [ ] framenet_v17........ FrameNet 1.7
  [ ] gazetteers.......... Gazeteer Lists
  [ ] genesis............. Genesis Corpus
  [ ] gutenberg........... Project Gutenberg Selections
  [ ] ieer................ NIST IE-ER DATA SAMPLE
  [ ] inaugural........... C-Span Inaugural Address Corpus
  [ ] indian.............. Indian Language POS-Tagged Corpus
Hit Enter to continue:
  [ ] jeita............... JEITA Public Morphologically Tagged Corpus (in
                           ChaSen format)
  [ ] kimmo............... PC-KIMMO Data Files
  [ ] knbc................ KNB Corpus (Annotated blog corpus)
  [ ] large_grammars...... Large context-free and feature-based grammars
                           for parser comparison
  [ ] lin_thesaurus....... Lin's Dependency Thesaurus
  [ ] mac_morpho.......... MAC-MORPHO: Brazilian Portuguese news text with
                           part-of-speech tags
  [ ] machado............. Machado de Assis -- Obra Completa
  [ ] masc_tagged......... MASC Tagged Corpus
  [ ] maxent_ne_chunker... ACE Named Entity Chunker (Maximum entropy)
  [ ] maxent_ne_chunker_tab ACE Named Entity Chunker (Maximum entropy)
  [ ] maxent_treebank_pos_tagger Treebank Part of Speech Tagger (Maximum entropy)
  [ ] maxent_treebank_pos_tagger_tab Treebank Part of Speech Tagger (Maximum entropy)
  [ ] mock_corpus......... Mock Corpus
  [ ] moses_sample........ Moses Sample Models
  [ ] movie_reviews....... Sentiment Polarity Dataset Version 2.0
  [ ] mte_teip5........... MULTEXT-East 1984 annotated corpus 4.0
  [ ] mwa_ppdb............ The monolingual word aligner (Sultan et al.
                           2015) subset of the Paraphrase Database.
Hit Enter to continue:
  [ ] names............... Names Corpus, Version 1.3 (1994-03-29)
  [ ] nombank.1.0......... NomBank Corpus 1.0
  [ ] nonbreaking_prefixes Non-Breaking Prefixes (Moses Decoder)
  [ ] nps_chat............ NPS Chat
  [ ] omw-1.4............. Open Multilingual Wordnet
  [ ] omw................. Open Multilingual Wordnet
  [ ] opinion_lexicon..... Opinion Lexicon
  [ ] panlex_swadesh...... PanLex Swadesh Corpora
  [ ] paradigms........... Paradigm Corpus
  [ ] pe08................ Cross-Framework and Cross-Domain Parser
                           Evaluation Shared Task
  [ ] perluniprops........ perluniprops: Index of Unicode Version 7.0.0
                           character properties in Perl
  [ ] pil................. The Patient Information Leaflet (PIL) Corpus
  [ ] pl196x.............. Polish language of the XX century sixties
  [ ] porter_test......... Porter Stemmer Test Files
  [ ] ppattach............ Prepositional Phrase Attachment Corpus
  [ ] problem_reports..... Problem Report Corpus
  [ ] product_reviews_1... Product Reviews (5 Products)
  [ ] product_reviews_2... Product Reviews (9 Products)
  [ ] propbank............ Proposition Bank Corpus 1.0
Hit Enter to continue:
  [ ] pros_cons........... Pros and Cons
  [ ] ptb................. Penn Treebank
  [ ] punkt............... Punkt Tokenizer Models
  [ ] punkt_tab........... Punkt Tokenizer Models
  [ ] qc.................. Experimental Data for Question Classification
  [ ] reuters............. The Reuters-21578 benchmark corpus, ApteMod
                           version
  [ ] rslp................ RSLP Stemmer (Removedor de Sufixos da Lingua
                           Portuguesa)
  [ ] rte................. PASCAL RTE Challenges 1, 2, and 3
  [ ] sample_grammars..... Sample Grammars
  [ ] semcor.............. SemCor 3.0
  [ ] senseval............ SENSEVAL 2 Corpus: Sense Tagged Text
  [ ] sentence_polarity... Sentence Polarity Dataset v1.0
  [ ] sentiwordnet........ SentiWordNet
  [ ] shakespeare......... Shakespeare XML Corpus Sample
  [ ] sinica_treebank..... Sinica Treebank Corpus Sample
  [ ] smultron............ SMULTRON Corpus Sample
  [ ] snowball_data....... Snowball Data
  [ ] spanish_grammars.... Grammars for Spanish
  [ ] state_union......... C-Span State of the Union Address Corpus
Hit Enter to continue:
  [ ] stopwords........... Stopwords Corpus
  [ ] subjectivity........ Subjectivity Dataset v1.0
  [ ] swadesh............. Swadesh Wordlists
  [ ] switchboard......... Switchboard Corpus Sample
  [ ] tagsets............. Help on Tagsets
  [ ] tagsets_json........ Help on Tagsets (JSON)
  [ ] timit............... TIMIT Corpus Sample
  [ ] toolbox............. Toolbox Sample Files
  [ ] treebank............ Penn Treebank Sample
  [ ] twitter_samples..... Twitter Samples
  [ ] udhr2............... Universal Declaration of Human Rights Corpus
                           (Unicode Version)
  [ ] udhr................ Universal Declaration of Human Rights Corpus
  [ ] unicode_samples..... Unicode Samples
  [ ] universal_tagset.... Mappings to the Universal Part-of-Speech Tagset
  [ ] universal_treebanks_v20 Universal Treebanks Version 2.0
  [ ] vader_lexicon....... VADER Sentiment Lexicon
  [ ] verbnet3............ VerbNet Lexicon, Version 3.3
  [ ] verbnet............. VerbNet Lexicon, Version 2.1
  [ ] webtext............. Web Text Corpus
  [ ] wmt15_eval.......... Evaluation data from WMT15
Hit Enter to continue:
  [ ] word2vec_sample..... Word2Vec Sample
  [ ] wordnet2021......... Open English Wordnet 2021
  [ ] wordnet2022......... Open English Wordnet 2022
  [ ] wordnet31........... Wordnet 3.1
  [ ] wordnet............. WordNet
  [ ] wordnet_ic.......... WordNet-InfoContent
  [ ] words............... Word Lists
  [ ] ycoe................ York-Toronto-Helsinki Parsed Corpus of Old
                           English Prose

Collections:
  [ ] all-corpora......... All the corpora
  [ ] all-nltk............ All packages available on nltk_data gh-pages
                           branch
  [ ] all................. All packages
  [ ] book................ Everything used in the NLTK Book
  [ ] popular............. Popular packages
  [ ] tests............... Packages for running tests
  [ ] third-party......... Third-party data packages

([*] marks installed packages)

Download which package (l=list; x=cancel)?
  Identifier> l
Packages:
  [ ] abc................. Australian Broadcasting Commission 2006
  [ ] alpino.............. Alpino Dutch Treebank
  [ ] averaged_perceptron_tagger Averaged Perceptron Tagger
  [ ] averaged_perceptron_tagger_eng Averaged Perceptron Tagger (JSON)
  [ ] averaged_perceptron_tagger_ru Averaged Perceptron Tagger (Russian)
  [ ] averaged_perceptron_tagger_rus Averaged Perceptron Tagger (Russian)
  [ ] basque_grammars..... Grammars for Basque
  [ ] bcp47............... BCP-47 Language Tags
  [ ] biocreative_ppi..... BioCreAtIvE (Critical Assessment of Information
                           Extraction Systems in Biology)
  [ ] bllip_wsj_no_aux.... BLLIP Parser: WSJ Model
  [ ] book_grammars....... Grammars from NLTK Book
  [ ] brown............... Brown Corpus
  [ ] brown_tei........... Brown Corpus (TEI XML Version)
  [ ] cess_cat............ CESS-CAT Treebank
  [ ] cess_esp............ CESS-ESP Treebank
  [ ] chat80.............. Chat-80 Data Files
  [ ] city_database....... City Database
  [ ] cmudict............. The Carnegie Mellon Pronouncing Dictionary (0.6)
  [ ] comparative_sentences Comparative Sentence Dataset
Hit Enter to continue:
  [ ] comtrans............ ComTrans Corpus Sample
  [ ] conll2000........... CONLL 2000 Chunking Corpus
  [ ] conll2002........... CONLL 2002 Named Entity Recognition Corpus
  [ ] conll2007........... Dependency Treebanks from CoNLL 2007 (Catalan
                           and Basque Subset)
  [ ] crubadan............ Crubadan Corpus
  [ ] dependency_treebank. Dependency Parsed Treebank
  [ ] dolch............... Dolch Word List
  [ ] english_wordnet..... Open English Wordnet
  [ ] europarl_raw........ Sample European Parliament Proceedings Parallel
                           Corpus
  [ ] extended_omw........ Extended Open Multilingual WordNet
  [ ] floresta............ Portuguese Treebank
  [ ] framenet_v15........ FrameNet 1.5
  [ ] framenet_v17........ FrameNet 1.7
  [ ] gazetteers.......... Gazeteer Lists
  [ ] genesis............. Genesis Corpus
  [ ] gutenberg........... Project Gutenberg Selections
  [ ] ieer................ NIST IE-ER DATA SAMPLE
  [ ] inaugural........... C-Span Inaugural Address Corpus
  [ ] indian.............. Indian Language POS-Tagged Corpus
Hit Enter to continue:
  [ ] jeita............... JEITA Public Morphologically Tagged Corpus (in
                           ChaSen format)
  [ ] kimmo............... PC-KIMMO Data Files
  [ ] knbc................ KNB Corpus (Annotated blog corpus)
  [ ] large_grammars...... Large context-free and feature-based grammars
                           for parser comparison
  [ ] lin_thesaurus....... Lin's Dependency Thesaurus
  [ ] mac_morpho.......... MAC-MORPHO: Brazilian Portuguese news text with
                           part-of-speech tags
  [ ] machado............. Machado de Assis -- Obra Completa
  [ ] masc_tagged......... MASC Tagged Corpus
  [ ] maxent_ne_chunker... ACE Named Entity Chunker (Maximum entropy)
  [ ] maxent_ne_chunker_tab ACE Named Entity Chunker (Maximum entropy)
  [ ] maxent_treebank_pos_tagger Treebank Part of Speech Tagger (Maximum entropy)
  [ ] maxent_treebank_pos_tagger_tab Treebank Part of Speech Tagger (Maximum entropy)
  [ ] mock_corpus......... Mock Corpus
  [ ] moses_sample........ Moses Sample Models
  [ ] movie_reviews....... Sentiment Polarity Dataset Version 2.0
  [ ] mte_teip5........... MULTEXT-East 1984 annotated corpus 4.0
  [ ] mwa_ppdb............ The monolingual word aligner (Sultan et al.
                           2015) subset of the Paraphrase Database.
Hit Enter to continue:
  [ ] names............... Names Corpus, Version 1.3 (1994-03-29)
  [ ] nombank.1.0......... NomBank Corpus 1.0
  [ ] nonbreaking_prefixes Non-Breaking Prefixes (Moses Decoder)
  [ ] nps_chat............ NPS Chat
  [ ] omw-1.4............. Open Multilingual Wordnet
  [ ] omw................. Open Multilingual Wordnet
  [ ] opinion_lexicon..... Opinion Lexicon
  [ ] panlex_swadesh...... PanLex Swadesh Corpora
  [ ] paradigms........... Paradigm Corpus
  [ ] pe08................ Cross-Framework and Cross-Domain Parser
                           Evaluation Shared Task
  [ ] perluniprops........ perluniprops: Index of Unicode Version 7.0.0
                           character properties in Perl
  [ ] pil................. The Patient Information Leaflet (PIL) Corpus
  [ ] pl196x.............. Polish language of the XX century sixties
  [ ] porter_test......... Porter Stemmer Test Files
  [ ] ppattach............ Prepositional Phrase Attachment Corpus
  [ ] problem_reports..... Problem Report Corpus
  [ ] product_reviews_1... Product Reviews (5 Products)
  [ ] product_reviews_2... Product Reviews (9 Products)
  [ ] propbank............ Proposition Bank Corpus 1.0
Hit Enter to continue:
  [ ] pros_cons........... Pros and Cons
  [ ] ptb................. Penn Treebank
  [ ] punkt............... Punkt Tokenizer Models
  [ ] punkt_tab........... Punkt Tokenizer Models
  [ ] qc.................. Experimental Data for Question Classification
  [ ] reuters............. The Reuters-21578 benchmark corpus, ApteMod
                           version
  [ ] rslp................ RSLP Stemmer (Removedor de Sufixos da Lingua
                           Portuguesa)
  [ ] rte................. PASCAL RTE Challenges 1, 2, and 3
  [ ] sample_grammars..... Sample Grammars
  [ ] semcor.............. SemCor 3.0
  [ ] senseval............ SENSEVAL 2 Corpus: Sense Tagged Text
  [ ] sentence_polarity... Sentence Polarity Dataset v1.0
  [ ] sentiwordnet........ SentiWordNet
  [ ] shakespeare......... Shakespeare XML Corpus Sample
  [ ] sinica_treebank..... Sinica Treebank Corpus Sample
  [ ] smultron............ SMULTRON Corpus Sample
  [ ] snowball_data....... Snowball Data
  [ ] spanish_grammars.... Grammars for Spanish
  [ ] state_union......... C-Span State of the Union Address Corpus
Hit Enter to continue:
  [ ] stopwords........... Stopwords Corpus
  [ ] subjectivity........ Subjectivity Dataset v1.0
  [ ] swadesh............. Swadesh Wordlists
  [ ] switchboard......... Switchboard Corpus Sample
  [ ] tagsets............. Help on Tagsets
  [ ] tagsets_json........ Help on Tagsets (JSON)
  [ ] timit............... TIMIT Corpus Sample
  [ ] toolbox............. Toolbox Sample Files
  [ ] treebank............ Penn Treebank Sample
  [ ] twitter_samples..... Twitter Samples
  [ ] udhr2............... Universal Declaration of Human Rights Corpus
                           (Unicode Version)
  [ ] udhr................ Universal Declaration of Human Rights Corpus
  [ ] unicode_samples..... Unicode Samples
  [ ] universal_tagset.... Mappings to the Universal Part-of-Speech Tagset
  [ ] universal_treebanks_v20 Universal Treebanks Version 2.0
  [ ] vader_lexicon....... VADER Sentiment Lexicon
  [ ] verbnet3............ VerbNet Lexicon, Version 3.3
  [ ] verbnet............. VerbNet Lexicon, Version 2.1
  [ ] webtext............. Web Text Corpus
  [ ] wmt15_eval.......... Evaluation data from WMT15
Hit Enter to continue:
  [ ] word2vec_sample..... Word2Vec Sample
  [ ] wordnet2021......... Open English Wordnet 2021
  [ ] wordnet2022......... Open English Wordnet 2022
  [ ] wordnet31........... Wordnet 3.1
  [ ] wordnet............. WordNet
  [ ] wordnet_ic.......... WordNet-InfoContent
  [ ] words............... Word Lists
  [ ] ycoe................ York-Toronto-Helsinki Parsed Corpus of Old
                           English Prose

Collections:
  [ ] all-corpora......... All the corpora
  [ ] all-nltk............ All packages available on nltk_data gh-pages
                           branch
  [ ] all................. All packages
  [ ] book................ Everything used in the NLTK Book
  [ ] popular............. Popular packages
  [ ] tests............... Packages for running tests
  [ ] third-party......... Third-party data packages

([*] marks installed packages)

Download which package (l=list; x=cancel)?
  Identifier> l
Packages:
  [ ] abc................. Australian Broadcasting Commission 2006
  [ ] alpino.............. Alpino Dutch Treebank
  [ ] averaged_perceptron_tagger Averaged Perceptron Tagger
  [ ] averaged_perceptron_tagger_eng Averaged Perceptron Tagger (JSON)
  [ ] averaged_perceptron_tagger_ru Averaged Perceptron Tagger (Russian)
  [ ] averaged_perceptron_tagger_rus Averaged Perceptron Tagger (Russian)
  [ ] basque_grammars..... Grammars for Basque
  [ ] bcp47............... BCP-47 Language Tags
  [ ] biocreative_ppi..... BioCreAtIvE (Critical Assessment of Information
                           Extraction Systems in Biology)
  [ ] bllip_wsj_no_aux.... BLLIP Parser: WSJ Model
  [ ] book_grammars....... Grammars from NLTK Book
  [ ] brown............... Brown Corpus
  [ ] brown_tei........... Brown Corpus (TEI XML Version)
  [ ] cess_cat............ CESS-CAT Treebank
  [ ] cess_esp............ CESS-ESP Treebank
  [ ] chat80.............. Chat-80 Data Files
  [ ] city_database....... City Database
  [ ] cmudict............. The Carnegie Mellon Pronouncing Dictionary (0.6)
  [ ] comparative_sentences Comparative Sentence Dataset
Hit Enter to continue:
  [ ] comtrans............ ComTrans Corpus Sample
  [ ] conll2000........... CONLL 2000 Chunking Corpus
  [ ] conll2002........... CONLL 2002 Named Entity Recognition Corpus
  [ ] conll2007........... Dependency Treebanks from CoNLL 2007 (Catalan
                           and Basque Subset)
  [ ] crubadan............ Crubadan Corpus
  [ ] dependency_treebank. Dependency Parsed Treebank
  [ ] dolch............... Dolch Word List
  [ ] english_wordnet..... Open English Wordnet
  [ ] europarl_raw........ Sample European Parliament Proceedings Parallel
                           Corpus
  [ ] extended_omw........ Extended Open Multilingual WordNet
  [ ] floresta............ Portuguese Treebank
  [ ] framenet_v15........ FrameNet 1.5
  [ ] framenet_v17........ FrameNet 1.7
  [ ] gazetteers.......... Gazeteer Lists
  [ ] genesis............. Genesis Corpus
  [ ] gutenberg........... Project Gutenberg Selections
  [ ] ieer................ NIST IE-ER DATA SAMPLE
  [ ] inaugural........... C-Span Inaugural Address Corpus
  [ ] indian.............. Indian Language POS-Tagged Corpus
Hit Enter to continue:
  [ ] jeita............... JEITA Public Morphologically Tagged Corpus (in
                           ChaSen format)
  [ ] kimmo............... PC-KIMMO Data Files
  [ ] knbc................ KNB Corpus (Annotated blog corpus)
  [ ] large_grammars...... Large context-free and feature-based grammars
                           for parser comparison
  [ ] lin_thesaurus....... Lin's Dependency Thesaurus
  [ ] mac_morpho.......... MAC-MORPHO: Brazilian Portuguese news text with
                           part-of-speech tags
  [ ] machado............. Machado de Assis -- Obra Completa
  [ ] masc_tagged......... MASC Tagged Corpus
  [ ] maxent_ne_chunker... ACE Named Entity Chunker (Maximum entropy)
  [ ] maxent_ne_chunker_tab ACE Named Entity Chunker (Maximum entropy)
  [ ] maxent_treebank_pos_tagger Treebank Part of Speech Tagger (Maximum entropy)
  [ ] maxent_treebank_pos_tagger_tab Treebank Part of Speech Tagger (Maximum entropy)
  [ ] mock_corpus......... Mock Corpus
  [ ] moses_sample........ Moses Sample Models
  [ ] movie_reviews....... Sentiment Polarity Dataset Version 2.0
  [ ] mte_teip5........... MULTEXT-East 1984 annotated corpus 4.0
  [ ] mwa_ppdb............ The monolingual word aligner (Sultan et al.
                           2015) subset of the Paraphrase Database.
Hit Enter to continue:
  [ ] names............... Names Corpus, Version 1.3 (1994-03-29)
  [ ] nombank.1.0......... NomBank Corpus 1.0

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [20]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [2]:
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [3]:
import pandas as pd

In [6]:
data=pd.read_csv('/content/news.csv')
data.head()

                                                text  label
0  Gere faults Trump for blurring meaning of 'ref...      1
1  German parties start to find common ground in ...      1
2  Senate Democratic leader says Attorney General...      1
3  Tennis: Kyrgios fined $10,000 for Shanghai wal...      1
4   Trump Threw Mar-A-Lago Fundraiser For Woman A...      0

In [11]:
dataset=data.iloc[:, 0]
dataset

0        Gere faults Trump for blurring meaning of 'ref...
1        German parties start to find common ground in ...
2        Senate Democratic leader says Attorney General...
3        Tennis: Kyrgios fined $10,000 for Shanghai wal...
4         Trump Threw Mar-A-Lago Fundraiser For Woman A...
                               ...
45752     Heavily-Armed Man Claiming To Be Jesus Arrest...
45753    Evangelicals Across The Spectrum Are Clarifyin...
45754    Senators question Kaleo' $4,500 tag on opioid ...
45755     CNN Does NOT Hold Back; Completely Makes Fun ...
45756    U.S. judge throws out Texas voter ID law suppo...
Name: text, Length: 45757, dtype: object

In [24]:
sentence=[]
for i in range(len(dataset)):
  sentence+=nltk.sent_tokenize(dataset.iloc[i])
sentence

["Gere faults Trump for blurring meaning of 'refugee' and 'terrorist' BERLIN (Reuters) - Actor and activist Richard Gere said on Friday that U.S. President Donald Trump has managed to merge the meaning of the words “refugee” and “terrorist” in the minds of many Americans.",
 'Gere also told a news conference at the Berlin Film Festival just before the world premiere of his new film “The Dinner” that he found it discouraging to see term “refugee” go through such a dispiriting change of meaning in the United States.',
 '“The most horrible thing that Trump has done is conflated two words – refugee and terrorist,” Gere, 67, told more than 100 journalists.',
 '“It means the same thing in the U.S. now.',
 'That’s what he’s accomplished to a large segment of our population.” Trump ordered a travel ban on refugees and citizens from seven Muslim-majority countries on Jan. 27.',
 'A U.S. appeal court in San Francisco refused to reinstate a temporary ban on the order.',
 'Trump criticized the court decision.',
 '“A ‘refugee’ used to be someone that we had empathy for ...someone we wanted to help who we wanted to give refuge to,” Gere said.',
 '“...Now we’re afraid of them and this ...is the biggest crime in itself: conflating these two ideas.” Gere met Chancellor Angela Merkel this week while in Berlin for the festival.',
 'She told Trump in a phone call two weeks ago the global fight against terrorism was no excuse for banning people from Muslim-majority countries.',
 'In the film “The Dinner”, Gere plays a famous politician who meets his wife and his brother at a hip restaurant to discuss a horrible crime committed by their sons.',
 'In an interview with Reuters before the news conference, Gere said he was encouraged by protests in the United States against Trump’s policies.',
 '“I am essentially an optimist so I am seeing this as an opportunity for people to show up the day after he was inaugurated,” Gere said.',
 '“There were millions of people in the streets in New York.',
 'It wasn’t angry demonstrations.',
 'It was positive demonstrations that were kind of a unity of purpose.” More than a million migrants, many of them fleeing conflict and persecution, have arrived in Germany over the last two years.',
 '“The Dinner” is one of 18 films at the ‘Berlinale’, competing for Golden and Silver Bears.',
 'The festival runs until Feb. 19.',
 'German parties start to find common ground in coalition talks BERLIN (Reuters) - Parties seeking to form Germany s next government found common ground in areas of social policy and digital infrastructure on Monday, but remain far apart on issues that provoked stormy clashes last week.',
 'Talks between conservatives, Greens and Free Democrats (FDP) resumed on Monday after Chancellor Angela Merkel convened a weekend meeting to clear the air between ideologically diverse parties forced by electoral arithmetic into awkward partnership.',
 'The weekend pause for thought did us good,  said Andreas Scheuer, a leader in the conservative Christian Social Union (CSU), the Bavarian sister party to Merkel s Christian Democrats (CDU).',
 'Other party leaders agreed.',
 'But Monday s talks, on education, digitalization, pensions and labor issues, as well as domestic security, were always expected to be less contentious than the immigration, fiscal and climate policies that divided them last week.',
 'One sign of the division came in an interview Merkel ally Peter Altmaier gave to the newspaper Die Zeit, where he shot down media reports about a reshuffling of ministerial portfolios.',
 'Der Spiegel magazine reported the FDP might head a weakened finance ministry, with key European affairs functions hived off to another ministry.',
 'The finance ministry is a strong ministry and should remain so in future,  Altmaier told Die Zeit.',
 'Altmaier runs Merkel s office and has been acting finance minister since Wolfgang Schaeuble s move agreed last month to leave the post and become president of parliament .',
 'Negotiators emerged on Monday with a document spelling out areas where they had reached agreement, including commitments to universal gigabit-speed internet by 2025, and spending 3.5 percent of economic output on research and development.',
 'After discussions that ran late into the evening, they also signed up to Merkel s election campaign pledge of achieving full employment, without giving a specific target date.',
 'Merkel, whose conservatives came first but lost seats in the Sept. 24 national elections must forge a so-called  Jamaica  coalition - named because the three camps  colors match that country s flag - that is untested at national level.',
 'Three more rounds of more detailed exploratory talks are planned for this week and four for next.',
 'If successful, the parties can then begin formal coalition talks.',
 'Senate Democratic leader says Attorney General Sessions should resign WASHINGTON (Reuters) - Senate Democratic leader Chuck Schumer said on Thursday that Attorney General Jeff Sessions had misled Congress over his contacts with a Russian official before the U.S. presidential election and for the good of the country should resign.',
 '“Attorney General Jeff Sessions had weeks to correct the record that he made before the Judiciary Committee but he let the record stand,” Schumer told a news conference.',
 '“Because the Department of Justice should be above reproach, for the good of the country Attorney General Sessions should resign,” he said.',
 "Tennis: Kyrgios fined $10,000 for Shanghai walk off Tennis - China Open - Men's Singles Finals - Beijing, China - October 8, 2017 - Nick Kyrgios of Australia reacts after losing a point against Rafael Nadal of Spain.",
 'REUTERS/Jason Lee\nLONDON (Reuters) - Australia’s Nick Kyrgios has been fined $10,000 and deducted his $21,000 first-round losers’ cheque following his decision to walk off after losing the first set against Steve Johnson in the Shanghai Masters on Tuesday.',
 'The tempestuous Kyrgios had just been beaten in a tiebreak against Johnson when he walked to the net, offered his hand to the American and stormed off court to the bemusement of his opponent and chair umpire Fergus Murphy.',
 'Kyrgios, 22, was booed off court by the crowd.',
 'The ATP said on Wednesday that Kyrgios had been punished for “unsportsmanlike conduct”, saying he had failed to complete a medical visit to explain his actions.',
 'Kyrgios, ranked 21 in the world, said later on Twitter that he had been suffering with a stomach bug and a shoulder problem.',
 '“I’ve been battling a stomach bug for the past 24 hours and I tried to be ready but I was really struggling on the court today which I think was pretty evident from the first point,” Kyrgios said.',
 '“My shoulder started to hurt in the practice which didn’t help either and once I lost the first set I was just not strong enough to continue.',
 'I’ve not eaten much in the past 24 hours.”\nLast year, Kyrgios was fined $16,500 and banned for eight weeks for deliberately throwing a game during his second-round defeat by Mischa Zverev in Shanghai.',
 'The ban for “conduct contrary to the integrity of the game” was reduced to three weeks after he agreed to a “care plan” under the direction of a sports psychologist.',
 'He was also docked a penalty point against world number one Rafael Nadal in the China Open final last week following a disagreement with the chair umpire.',
 ' Trump Threw Mar-A-Lago Fundraiser For Woman At The Center Of Bribery Scandal Just a few days after she made the decision to let an investigation of Donald Trump s Trump University slide, the former reality TV star held a fundraiser for Florida attorney general Pam Bondi at his palatial Mar-A-Lago compound.News of the cash-fueled party comes as Trump faces renewed criticism after being fined by the IRS after it came to light that the Trump Foundation illegally funneled money into Bondi s re-election campaign.In March 2014, Donald Trump opened his 126-room Palm Beach resort, Mar-a-Lago, for a $3,000-per-person fundraiser for Pam Bondi.',
 'The Florida attorney general, who was facing a tough re-election campaign, had recently decided not to investigate Trump University.Trump did not write a check to the attorney general that night.',
 'The previous fall, his personal foundation had given $25,000 to a pro-Bondi PAC.',
 'But by hosting her fundraiser at Mar-a-Lago and bringing in some of his own star power, Trump provided Bondi s campaign with a nice financial boost.The Huffington Post also reports that while Trump has billed the RNC $140,000 per event to use his mansion, he only charged the Republican Party of Florida $4,855.65.',
 'That means that Trump stands to make a windfall simply by controlling the flow of campaign donor money to his own enterprises.News of the interlocking relationship between Trump and Bondi (she has done campaign rallies for him) underscores how the national media has ignored or played down actual stories of Trump and his involvement with corruption.',
 'Instead they have banged the drums on the Clinton Foundation, making allegations of wrong-doing based on the potential and  optics  of the far-reaching charity the Clintons put in place.Trump is also implicated in similar behavior in Texas.',
 'The attorney general there dropped looking into Trump University a little after he gave him a financial donation.Featured image via Flickr',
 ' President Curtsy Delivers A Really Sick Burn To Manchester Attackers: ‘Losers!’ (VIDEO) Conservatives have suggested repeatedly that if former President Barack Obama clicked his heels together three times while saying the words  radical Islamic terrorism  then terror attacks would never happen again.',
 'Ever.',
 'During former reality show star Donald Trump s speech in Saudi Arabia, he failed to use those words, but it helped to elect him while on the campaign trail by criticizing his opponents for not saying the magical phrase.While Trump is visiting the Middle East, a bomb tore through an entrance hall of the Manchester Arena at about 10:30 p.m. as American pop star Ariana Grande s concert was ending.',
 'In total, 22 people died and 59 concert-goers were hospitalized, marking this as the deadliest terrorist assault in Britain since 2005.On Tuesday, ISIS claimed responsibility for the bombing.During President Curtsy s press conference with Palestinian Authority President Mahmoud Abbas, Trump branded terrorist groups as  evil losers.',
 'I extend my deepest condolences to those so terribly injured  and to the so many families of the victims.',
 'We stand in absolute solidarity with the people of the United Kingdom,  Trump said Tuesday.',
 'So many young beautiful and innocent people living and enjoying their lives, murdered  by evil losers in life,  he said.',
 'I won t call them monsters because they would like that term,  he continued.',
 'They would think that s a great name.',
 'I will call them from now on losers because that s what they are, they re losers.',
 'And we ll have more of them.',
 'But they re losers, just remember that.',
 'The terrorists and extremists and those who give them aid and comfort must be driven out from our society forever,  he added, then called on the international community to  protect human life.',
 'Watch Trump deliver a real sick burn to terrorists everywhere by calling them  evil losers.',
 'You know, as opposed to evil winners.On the campaign trail, Donald Trump said he would present a plan to defeat the Islamic State to his generals within 30 days after taking office, but that hasn t happened.Photo by Chip Somodevilla/Getty Images.',
 'NSA risks talent exodus amid morale slump, Trump fears WASHINGTON (Reuters) - The National Security Agency risks a brain-drain of hackers and cyber spies due to a tumultuous reorganization and worries about the acrimonious relationship between the intelligence community and President Donald Trump, according to current and former NSA officials and cybersecurity industry sources.',
 'Half-a-dozen cybersecurity executives told Reuters they had witnessed a marked increase in the number of U.S. intelligence officers and government contractors seeking employment in the private sector since Trump took office on Jan. 20.',
 'One of the executives, who would speak only on condition of anonymity, said he was stunned by the caliber of the would-be recruits.',
 'They are coming from a variety of government intelligence and law enforcement agencies, multiple executives said, and their interest stems in part from concerns about the direction of U.S intelligence agencies under Trump.',
 'Retaining and recruiting talented technical personnel has become a top national security priority in recent years as Russia, China, Iran and other nation states and criminal groups have sharpened their cyber offensive abilities.',
 'NSA and other intelligence agencies have long struggled to deter some of their best employees from leaving for higher-paying jobs in Silicon Valley and elsewhere.',
 'The problem is especially acute at NSA, current and former officials said, due to a reorganization known as NSA21 that began last year and aims to merge the agency’s electronic eavesdropping and domestic cyber-security operations.',
 'The two-year overhaul includes expanding parts of NSA that deal with business management and human resources and putting them on par with research and engineering.',
 'The aim is to “ensure that we’re using all of our resources to maximum effect to accomplish our mission,” NSA Director Mike Rogers said.',
 'The changes include new management structures that have left some career employees uncertain about their missions and  prospects.',
 'Former employees say the reorganization has failed to address widespread concerns that the agency is falling behind in exploiting private-sector technological breakthroughs.',
 'A former top NSA official said he had been told by three current officials that budget problems meant there was too little money for promotions.',
 'That is especially important for younger employees, who sometimes need two jobs to make ends meet in the expensive Washington D.C. area, the official said.',
 '“Morale is as low as I’ve ever seen it,” said another former senior NSA official, who maintains close contact with current employees.',
 'Asked about the risk of losing talent from NSA and other agencies, White House spokesman Michael Anton said Trump had sought to reassure the intelligence community by visiting the CIA headquarters on his first full day in office.',
 'Anton also pointed to the military spending increase in Trump’s budget proposal released on Monday.',
 'It will likely take more than a visit to the CIA to patch up relations with the intelligence community, the current and former officials said.',
 'Trump has attacked findings from intelligence agencies that Russia hacked emails belonging to Democratic Party operatives during the 2016 presidential campaign to help him win, though he did eventually accept the findings.',
 'In January, Trump accused intelligence agencies of leaking  false information and said it was reminiscent of tactics used in Nazi Germany.',
 'The breadth of any exodus from the NSA and other intelligence agencies is difficult to quantify.',
 'The NSA has “seen a steady rise” in the attrition rate among its roughly 36,000 employees since 2009, and it now sits at a “little less than six percent,” according to an NSA spokesman.',
 'NSA director Michael Rogers said last year that the attrition rate was 3.3 percent in 2015, suggesting a sharp jump in departures since then.',
 'Several senior NSA officials who have left or plan to leave, including deputy director Richard Ledgett and the head of cyber defense, Curtis Dukes, have said their departures were unrelated to Trump or the reorganization.',
 'Some turnover is normal with any new administration, government and industry officials noted, and a stronger economy has also improved pay and prospects in the private sector.',
 '“During this time the economy has been recovering from the recession, unemployment rates have been falling and the demand for highly skilled technical talent has been increasing,” an NSA spokesman said, when asked to comment on the reports of employee departures.',
 'In a statement, Kathy Hutson, NSA’s chief of human resources, said the agency continues “to attract amazing talent necessary to conduct the security mission the nation needs.” Some NSA veterans attribute the morale issues and staff departures to the leadership style of Rogers, who took over the spy agency in 2014 with the task of dousing an international furor caused by leaks from former contractor Edward Snowden.',
 'Concern about Rogers reached an apex last October, when former Defense Secretary Ash Carter and former Director of National Intelligence James Clapper recommended to then-President Barack Obama that Rogers be removed.',
 'The NSA did not respond to a request for comment on the recommendation last fall that Rogers be replaced.',
 'Rogers is now expected to retain his job at NSA for at least another year, according to former officials.',
 'Rogers acknowledged concerns about potential morale problems last month, telling a congressional committee that Trump’s broadsides against the intelligence community could create “a situation where our workforce decides to walk.”  Trump’s criticism of the intelligence community has exacerbated the stress caused by the reorganization at the NSA, said Susan Hennessey, a former NSA lawyer now with Brookings Institution.',
 'The “tone coming from the White House makes an already difficult situation worse, by eroding the sense of common purpose and service,” she said.',
 'A wave of departures of career personnel, Hennessey added,  “would represent an incalculable loss to national security.”',
 ' Trump Completely COLLAPSING In Most Important Republican State The only state keeping the Republican Party viable at the national level in presidential races is the state of Texas.',
 'Texas and its 38 electoral votes help to form the backbone in any Republican quest for the 270 electoral votes needed to win the presidency.Republicans have not lost Texas since 1976, when Jimmy Carter defeated Gerald Ford after Nixon resigned in the wake of the Watergate scandal.',
 'Whether Republicans have won or lost the overall race, Texas has been blood red (Mitt Romney won by 16% there in 2012).But now with Donald Trump as the Republican nominee, suddenly the race has seriously narrowed in Texas.Donald Trump is still winning in the deep red state, but his advantage has dropped precipitously from double digits to under 5 percent in the last two weeks.',
 'The last three polls in the state show him ahead of Hillary Clinton by only 2 points in a Washington Post-SurveyMonkey poll, 3 points in a University of Houston poll and 4 points in a Survey USA/Texas Tenga poll.All of those most recent polls were conducted after the Oct. 7 release of a tape in which Trump bragged about sexually assaulting women.',
 'Polls conducted in the prior month show the GOP candidate leading by at least 12 and up to 22 points.',
 'A couple of earlier polls had signaled the race might be closer than expected, but there hasn t been consistent evidence until now.A Clinton win in Texas isn t required for there to be considered a major ground-shifting development.',
 'Even a single-digit Texas loss would be a huge step forward for Democrats there, and a shock to the system for Republicans.The growing Latino population in Texas has consistently raised Democratic hopes that the state could be tipped into their column like it has been in Colorado, Nevada, and New Mexico.',
 'Democrats are also hoping for success in Arizona, where incumbent Senator John McCain recently denounced Trump for his crude comments with Billy Bush.Things are changing in the southwest, and they might change faster than anyone expected.Featured image via Flickr',

In [25]:
# lamitizing
lamitizer=nltk.stem.WordNetLemmatizer()